Various enhancements and fix for conditional moment
NREL/sup3r pull request #144
Opened 2023-03-23 15:10 UTC by malihass

- Add padding for end of time interval
- Fix simple enhancement for space and time used to create the sub filter
- Enable the use of linear time enhancement

2023-04-06 13:07 UTC, bnb32 requested changes

2023-04-06 13:07 UTC, bnb32 commented on sup3r/preprocessing/conditional_moment_batch_handling.py
> +        end_t_padding : bool | False
Could you expand this description a little. I don't totally understand the purpose of this arg.

2023-04-06 13:07 UTC, bnb32 commented on sup3r/preprocessing/conditional_moment_batch_handling.py
> +        temporal_enhancing_method : str
*constructing

2023-04-06 13:07 UTC, bnb32 commented on sup3r/preprocessing/conditional_moment_batch_handling.py
> +        temporal_enhancing_method : str
Can you explain the difference between constant/linear

2023-04-06 15:26 UTC, grantbuster commented
@malihass is this still draft?

2023-04-07 14:53 UTC, malihass commented
> @malihass is this still draft?

Yeah, I am running a few cases to verify that the linear time + the end padding work as expected. Eagle went back online so I'll try to process these asap and convert this to a regular PR

2023-04-07 15:14 UTC, grantbuster commented
> > @malihass is this still draft?
> 
> Yeah, I am running a few cases to verify that the linear time + the end padding work as expected. Eagle went back online so I'll try to process these asap and convert this to a regular PR

Cool, @bnb32 is drafting a new release (v0.1.0). Check in with him if you want these changes to be part of the release.

2023-04-13 21:21 UTC, bnb32 approved these changes
lgtm. thanks for the extra descriptions.

2023-04-13 22:02 UTC, merged