Bnb/log interp
NREL/sup3r pull request #155
Opened 2023-07-14 16:44 UTC by bnb32

2023-08-10 21:16 UTC, grantbuster requested changes

2023-08-10 21:16 UTC, grantbuster commented on sup3r/qa/bias_stats.py
> +                bias_df[cols] -= ref_df.iloc[self.ref_sites][cols].values
Is this just delta bias then? How is this different than the code in `sup3r/bias/bias_calc.py`? Do we really need another class for this? My understanding is that this just does a KDTree and diff between `TemporalStats` outputs?

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/era_downloader.py
> +    c = cdsapi.Client()
Global single-char variable? bad idea. Recommend `CDS_API_CLIENT` (all caps for global, multiple chars because easier to search and find)

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/era_downloader.py
> +                'sp': 'pressure_0m'}
this is just a personal thing, i always prefer global lists/dicts to have every entry on a different line. It's a lot easier to see what's there, what they keys are, and easier to add new items.

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/era_downloader.py
> +class EraDownloader(BaseEraDownloader):
why base/concrete classes? is BaseEraDownloader sub-classed somewhere else? Are there abstract methods?

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/interpolation.py
> +        """Interpolate var_array to given level(s) based on h_array.
h_array is not a thing?

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/log_interpolator.py
> +class LogLinInterpolator:
lots going on here any my review won't be thorough. Of all the new code, it seems like this should have tests though.

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/log_interpolator.py
> +"""Rescale ERA5 wind components according to log profile"""
nitpicky but i would name the file `interpolate_log_profile.py` so its next to the other interp file

2023-08-10 21:16 UTC, grantbuster commented on sup3r/utilities/log_interpolator.py
> +            log_ws = ws_log_profile(levels[lev_mask], *popt)
well this is nice and clean! all of the optimize methods from scipy are so overwhelming. glad you found one that works.

2023-08-11 12:22 UTC, bnb32 commented on sup3r/postprocessing/collection.py
> +    def get_target_and_masked_meta(self, meta, target_final_meta_file=None,
no problems just cleaning things up a little.

2023-08-17 20:59 UTC, grantbuster commented
@bnb32 looks good but still curious why you did BaseEraDownloader and EraDownloader. Seems like you're not using the base class. 

Also, in the future would you mind responding to all review comments? Otherwise you make me go through and manually check how you responded to all of them. This should be a dialogue, not just throwing stuff over the fence.

2023-08-17 21:06 UTC, bnb32 commented
> @bnb32 looks good but still curious why you did BaseEraDownloader and EraDownloader. Seems like you're not using the base class.
> 
> Also, in the future would you mind responding to all review comments? Otherwise you make me go through and manually check how you responded to all of them. This should be a dialogue, not just throwing stuff over the fence.

I used the Base class just because it felt cleaner. I put what seemed like more general methods there. Happy to combine them though. My bad about not responding, thought you would get notifications or something for what I did respond to and see code changes otherwise.

2023-08-17 21:19 UTC, grantbuster commented
> > @bnb32 looks good but still curious why you did BaseEraDownloader and EraDownloader. Seems like you're not using the base class.
> > Also, in the future would you mind responding to all review comments? Otherwise you make me go through and manually check how you responded to all of them. This should be a dialogue, not just throwing stuff over the fence.
> 
> @grantbuster I used the Base class just because it felt cleaner. I put what seemed like more general methods there. Happy to combine them though. My bad about not responding, thought you would get notifications or something for what I did respond to and see code changes otherwise.

Do you see a potential subclass using only the base class and not the full era downloader class? If not, i'd say combine them. Inheritance hierarchies should only be as deep as is strictly necessary. The purpose of abstraction is to provide a generic template for children classes. Without multiple children classes, it's just an unnecessary complication to structure IMO. 

Yeah I get like an email when you push to an open PR but it's much nicer to have responses to queries rather than digging through code (again) to figure out what you did and guessing on whether or not i think you addressed the question.

2023-08-17 21:21 UTC, bnb32 commented
> Do you see a potential subclass using only the base class and not the full era downloader class? If not, i'd say combine them. Inheritance hierarchies should only be as deep as is strictly necessary. The purpose of abstraction is to provide a generic template for children classes. Without multiple children classes, it's just an unnecessary complication to structure IMO.

@grantbuster  I could maybe envision something that downloads other data sources but its prob not worth keeping them separate right now. I hear ya on the responses :)
> 
> Yeah I get like an email when you push to an open PR but it's much nicer to have responses to queries rather than digging through code (again) to figure out what you did and guessing on whether or not i think you addressed the question.

2023-08-17 21:23 UTC, grantbuster commented
> > Do you see a potential subclass using only the base class and not the full era downloader class? If not, i'd say combine them. Inheritance hierarchies should only be as deep as is strictly necessary. The purpose of abstraction is to provide a generic template for children classes. Without multiple children classes, it's just an unnecessary complication to structure IMO.
> 
> @grantbuster I could maybe envision something that downloads other data sources but its prob not worth keeping them separate right now. I hear ya on the responses :)

Yeah i say let's merge them and then merge this PR! sweet!

2023-08-18 18:24 UTC, grantbuster approved these changes

2023-08-18 18:50 UTC, merged