Setup for Eagle
NREL/sup3r pull request #212
Opened 2024-05-02 04:34 UTC by castelao

Setup to run on Eagle.

2024-05-10 15:44 UTC, castelao commented
It's not worth to setup for Eagle considering it will be out soon. This setup shouldn't affect anyone but it would help me.

2024-05-10 15:54 UTC, grantbuster approved these changes
I'm still not familiar with the pixi setup so lgtm, but how are you using this? At this point i think i'm the only person running sup3r on eagle which is fine. You and brandon should focus on getting a kestrel gpu env setup with tensorflow version pinned. I'll finish model validation on Eagle and then we'll migrate things over when kestrel GPUs are available.

2024-05-10 22:49 UTC, bnb32 requested changes
looks good! small comment on netcdf vs h5netcdf. also, a key part of this is some additional instructions on use though. could you add some to the README?

2024-05-10 22:49 UTC, bnb32 commented on pyproject.toml
> +netcdf4 = ">=1.5.8"
I dont think we need both netcdf and h5netcdf

2024-05-13 14:14 UTC, castelao commented
> ... also, a key part of this is some additional instructions on use though. could you add some to the README?

Yes. I'm planning to add the instructions in a following PR. With this one here I can do some tests in kestrel, and tune it, before recommending you both on how to use it.

2024-05-13 14:16 UTC, bnb32 commented
> > ... also, a key part of this is some additional instructions on use though. could you add some to the README?
> 
> Yes. I'm planning to add the instructions in a following PR. With this one here I can do some tests in kestrel, and tune it, before recommending you both on how to use it.

Ok, that works.

2024-05-13 14:59 UTC, merged